# Generated by Django 3.2.4 on 2021-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=500)),
                ('user_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
