# Generated by Django 3.2.4 on 2021-07-17 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('users_subscribed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
