# Generated by Django 3.2.4 on 2021-07-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarticle',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='userarticle',
            name='subscriptions_feed',
        ),
        migrations.AddField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subscriptions_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subscriptionfeeds'),
        ),
        migrations.AddField(
            model_name='subscriptionfeeds',
            name='subscription_articles',
            field=models.ManyToManyField(null=True, to='main_app.Article'),
        ),
    ]
