# Generated by Django 3.2.4 on 2021-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_subscriptionfeeds_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeeds',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
