# Generated by Django 3.2.4 on 2021-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_subscriptionfeeds_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeeds',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
