# Generated by Django 3.2.4 on 2021-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_subscriptionfeeds_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeeds',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
