# Generated by Django 3.2.4 on 2021-07-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_article_subscriptions_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subscriptions_feed',
        ),
        migrations.AddField(
            model_name='article',
            name='subscriptions_feed',
            field=models.ManyToManyField(to='main_app.SubscriptionFeeds'),
        ),
    ]
