# Generated by Django 3.2.4 on 2021-07-21 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_subscriptionfeeds_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250)),
                ('summary', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=250)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subscriptionfeeds')),
                ('users_subscribed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
