# Generated by Django 3.2.4 on 2021-07-26 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_auto_20210726_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userarticle',
            unique_together={('article', 'user')},
        ),
    ]
