# Generated by Django 3.2.4 on 2021-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_userarticle_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_time',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionfeeds',
            name='link',
            field=models.URLField(max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userarticle',
            unique_together=set(),
        ),
    ]
