# Generated by Django 3.2.4 on 2021-07-27 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210727_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 13, 36, 0, 586954, tzinfo=utc)),
        ),
    ]
