# Generated by Django 3.2.4 on 2021-08-04 16:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userarticle',
            managers=[
                ('dahl_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
