# Generated by Django 3.2.4 on 2021-08-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_userarticle_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userarticle',
            managers=[
            ],
        ),
    ]
