# Generated by Django 3.2.4 on 2021-08-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_userfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolder',
            name='subscriptions_feed',
            field=models.ManyToManyField(blank=True, to='main_app.SubscriptionFeeds'),
        ),
    ]
